### ISSUE TITLE
Create multisig contract for sensitive functions

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#119]
We will not have a fully-functional Stacks multisig implementation before launch, which means we need a way to perform sensitive functions via a smart contract, e.g. updating the city wallet or upgrading the logic contract.

These should not be necessary, but having a mechanism in place now ensures we have a way to perform these functions in an emergency situation. 

Let's assume a `3 of 5` structure for approval but we may fall back to a `2 of 3`. Will confirm this today.

We can call it `citycoin-auth.clar`.

This would be used for:

- updating the city wallet address in the contract
- submitting an updated logic contract
- setting a new token URI

I'm pretty sure that's all the protected functions above, if I missed one let me know!

Notes from @LNow:

1. User A "register a function call" with all required parameters (sig 1 of 3)
2. User B can confirm or decline this "call" (sig 2 of 3)
3. User C can also confirm or decline (sig 3 of 3)

**Comment by hstove** [comment]
One way I'd thought of this kind of contract would be:

- It has some state for the "signers" - maybe a map or a list of principals.
- It has a map for "proposals" or something - and each proposal is just a principal (a contract that has an `execute` function)
- Each signer can vote on the proposal
- Once `approvals > min-signers`, call the `execute` function of the proposal (with `as-contract`)

this could generalize to basically anything. It could execute STX transfers or any function call. A downside is that you have to make a new contract for every proposal.

**Comment by LNow** [comment]
@hstove you are genius. Pure genius!!!

My main idea was to define all possible calls in one contract. Everything else like you described. But you took it to a whole new level.

What do you think about something like this:

### proposal-trait
```clarity
;; simple trait tat all executable proposals must implement
(define-trait proposal-trait (
  (execute () (response bool uint))
))
```

### citycoin-auth
```
(use-trait proposal-trait .proposal-trait.proposal-trait)

(define-map Proposals
  principal
  {
    votes: uint,
    executed: bool
  }
)

(define-map Votes
  { proposal: principal, voter: principal}
  bool
)

(define-public (add-proposal (proposal <proposal-trait>))
  (begin
    ;; some security checks
    (map-set Proposals 
      (contract-of proposal) 
      { 
        votes: u0, 
        executed: false
      }
    )
    (ok true)
  )
)

(define-public (vote (proposal <proposal-trait>))
  (let
    (
      (proposalAddr (contract-of proposal))
      (proposalData (unwrap! (map-get? Proposals proposalAddr) (err "not found")))
    )
    ;; some security checks
    (map-set Proposals proposalAddr
      (merge proposalData { votes: (+ (get votes proposalData) u1) })
    )
    (map-set Votes 
      { proposal: proposalAddr, voter: tx-sender }
      true
    )
    (ok true)
  )
)

;; executing could be also part of the voting mechanism
(define-public (execute (proposal <proposal-trait>))
  (let
    (
      (proposalAddr (contract-of proposal))
      (proposalData (unwrap! (map-get? Proposals proposalAddr) (err "not found")))
    )
    ;; some security checks
    (try! (as-contract (contract-call? proposal execute)))
    (map-set Proposals proposalAddr 
      (merge proposalData { executed: true })
    )
    (ok true)
  )
)
```

### Proposal 1 - sets new city wallet
```clarity
(impl-trait .proposal-trait.proposal-trait)

(define-constant ERR_UNAUTHORIZED u4000)

(define-public (execute)
  (begin
    (asserts! (is-eq contract-caller .citycoin-auth) (err ERR_UNAUTHORIZED))
    (contract-call? .core set-city-wallet 'ST3DG3R65C9TTEEW5BC5XTSY0M1JM7NBE7GVWKTVJ)
  )
)
```

**Comment by hstove** [comment]
This is awesome, looks perfect! The use of a votes map is so much more than my list/fold approach, I'm going to steal that :)

**Comment by hstove** [comment]
I'm just free-thinking here, and I don't think this should be necessary for your implementation.

If we were going to generalize this and make a web app that is a generic multi-sig smart wallet, how could we design contracts that allow you to re-use logic and not have to deploy a new contract every single time, at least for common actions?

Deploying a new contract slightly increases the chance of a bug or missed logic. For most cases, the signers can check the contract against some "known" contract and should be able to see that only a number or address was changed. 

I think we could abstract this just slightly. Imagine we want to design a meta-contract that allows a "smart wallet" to execute a stacking operation. The code is 99% the same - we just need to change the `amount`, `cycles`, and `pox-addr`.

What if we changed the `execute` method to have the signature `(execute (id (optional uint)))`? Then, our "stacking contract" could support specifying domain-specific data for each `id`. So the flow would be something like:

- Call `stacking-executer`'s `create-params` method with some data like `pox-addr`, `cycles`, `amount`. This generates a new `id` and stores the data in a map. 
- Call `add-proposal` with the above contract and our newly generated "param ID". This gets saved just like the above, but including the `id`.
- When voting on a proposal, you include the optional `id`
- (all the above steps could be in one 'initialization' function call)
- When executing the proposal, we call `execute(id)` on the proposal contract.
- The stacking executer gets the necessary data from this `id` and executes the stacking operation

This way, we can create audited contracts that are built for common operations. I'd imagine these kinds of things could be stacking, transfering STX/FT/NFT, BNS, etc.

If there was an associated web app, the web app could "know" about these special contracts and make the UX really easy for proposers and signers.

Again, **I don't think you should take this on for the citycoins implementation**, just a thought for a longer-term vision for this. If we went down this path, we'd probably want to abstract the "smart wallet" contract to store individual groups for each set of signers, so that we don't need to re-deploy the same contract for new signers.

**Comment by hstove** [comment]
I know you haven't added safety checks yet, but one thing I find helpful is to use `map-insert` instead of `map-set` for things like this. It will return `false` (and not insert) if the record already exists. So you easily do things like `(asserts! (map-insert ...) (err ERR_ALREADY_VOTED))`

**Comment by LNow** [comment]
We can make it very, very, very flexible :)

Sample implementation: https://github.com/LNow/executable-proposals/tree/main/contracts
 - you can create proposal using external contract that implements `proposal-trait`, but at the beginning proposal is not active so you can't vote on it nor execute it.
 - you can add as many named arguments as you might need to execute your proposal (for now it allows only `uint`, `int` and `principal` types)
 - once you have your proposal fully defined, you activate it
 - users vote on it (right now it's just simple function without much logic)
 - you can execute your proposal and contract will pas to your executable contract and ID that it can use to get values of all those named arguments you defined earlier.

With a bit of "love" it could be quite cool little project ;)

In **CityCoins** we probably use some mix of few approach discussed here. Flexible enough to handle potential future needs, but easy to implement to not cause any delays.

**Comment by hstove** [comment]
Damn, really smart!

One aspect of this is that you want to make it dead simple for a signer to know what arguments have been included for a proposal. With this exact interface, I'm not sure if it's possible to easily pull all the arguments for a proposal.

I think this is better than what I had suggested, though, because it provides a standard method for these "proposal arguments". If we're imagining a wallet that can pull and show arguments, then having this built-in makes a lot more sense.

I know you're busy, but I would definitely put some STX towards a grant if someone wanted to own this project all the way through (contracts, app, etc)

**Comment by LNow** [comment]
> One aspect of this is that you want to make it dead simple for a signer to know what arguments have been included for a proposal. With this exact interface, I'm not sure if it's possible to easily pull all the arguments for a proposal.

It was just a quick draft.
In next revision instead of `get-uint-argument` it will have 4 functions:
- `(get-uint-arg-by-name (proposalId uint) (name (string-ascii 255)))` that will return  `{ argumentId: uint, value: uint }`
- `(get-uint-arg-by-name (proposalId uint) (name (string-ascii 255)))` that will return `(optional uint)`
- `(get-uint-arg-by-id (proposalId uint) (argumentId uint))` that will return `{ name: name, value: value}`
- `(get-uint-val-by-id (proposalId uint) (argumentId uint))` that will return `(optional uint)`

Plus extra `(get-proposal-last-arg-id (proposalId uint) (datatype (string-ascii 25)))` that will tell you what is the last argument ID of specific type.

With this building UI should not be that difficult.
1. Call `(get-proposals-last-arg-id u10 "uint")` - returned 3
2. Call `(get-uint-arg-by-id u10 u1)`, `(get-uint-arg-by-id u10 u2)`, `(get-uint-arg-by-id u10 u3)`
and that's it :)


> I know you're busy, but I would definitely put some STX towards a grant if someone wanted to own this project all the way through (contracts, app, etc)

For CityCoins we'll gonna have almost all feature.
The only thing that we won't have is extensible/dynamic list of approved voters. We gonna use fixed list. 
Adding voters list owned and maintained by proposal creator using map, or allowing to specify for each proposal an external contract that will validate if user is eligible to vote or not should be doable. And I know at least few Clarity developers (including you @hstove ) who could handle that things with ease :wink:

**Comment by hstove** [comment]
Yeah that all makes sense!

Regarding my suggestion for the contract supporting multiple different groups, unfortunately I don't think that'll work. Part of the point of this is so that the wallet can hold assets as a principal, and it wouldn't be possible to segregate different assets and principal-based state for different groups.

Which is fine though! Makes things simpler

**Comment by LNow** [comment]
You meant something like this?

<details>
  <summary>Click to see sample code</summary>

   ```clarity
;; ERRORS
(define-constant ERR_UNKNOWN_GROUP u5000)

(define-data-var lastGroupId uint u0)

;; here we gonna track uSTX donated per group
(define-map Groups
  uint ;; groupId
  {
    creator: principal,
    name: (string-ascii 255),
    ustx: uint
  }
)

;; Here we gonna track uSTX donated to all groups combined together
;; 
;; If value stored in this variable is smaller than (stx-get-balance (as-contract tx-sender)) 
;; it means that someone submitted uSTX directly to the contract address.
;; You can create extra function that will allow contract owner withdraw such "free uSTX", but
;; any other funds will be disposable only to groups they've been donated to.
(define-data-var allGroupsUstx uint u0)

(define-public (create-group (name (string-ascii 255)))
  (let
    ((groupId (+ (var-get lastGroupId) u1)))
    (map-set Groups groupId { creator: contract-caller, name: name, ustx: u0 })
    (ok groupId)
  )
)

(define-read-only (get-group (groupId uint))
  (map-get? Groups groupId)
)

(define-public (donate-ustx (groupId uint) (amount uint))
  (let
    (
      (group (unwrap! (get-group groupId) (err ERR_UNKNOWN_GROUP)))
    )
    (map-set Groups 
      groupId 
      (merge group { ustx: (+ (get ustx group) amount) })
    )
    (var-set allGroupsUstx (+ (var-get allGroupsUstx) amount))
    (try! (stx-transfer? amount tx-sender (as-contract tx-sender)))
    (ok true)
  )
)
```
</details>
If you want we can open a discussion about it in repo I linked previously.

**Comment by LNow** [comment]
@whoabuddy I have a dilemma regarding how we should connect `citycoin-auth` with rest of our contracts.

1. Where we should keep list of authorized voters? In `auth`? In `core`?
2. Do we want to create small dedicated contracts for all functions that need to be secured with voting (ie. one function = one contract) and then couple them with our existing contracts?  Or do we want to extend our contracts with functions like presented below?

```clarity
;; In order to secure setting up new city wallet address in core contract we would add to core 2 functions:

;; this function will register in auth contract new proposal with newCityWallet argument
(define-public (create-set-city-wallet-proposal (newCityWallet principal))
  (let
    (
      (self (as-contract tx-sender))
    )
    ;; security checks ensures only authorized wallet can create proposal
    (match (as-contract (contract-call? .citycoin-auth add-proposal self)) proposalId
      (begin
        (try! (as-contract (contract-call? .citycoin-auth add-principal-argument proposalId "newCityWallet" principal)))
        (try! (as-contract (contract-call? .citycoin-auth activate-proposal proposalId)))
      )
      error (err error)
    ) 
  )
)

;; this function executes proposal registered with previous function
(define-public (execute-set-city-wallet-proposal (proposalId uint))
  (let
    (
      (newCityWallet (unwrap! (contract-call? .citycoin-auth get-principal-value-by-name proposalId "newCityWallet") (err ERR_ARGUMENT_MISSING))
    )
    (asserts! (contract-call? .citycoin-auth can-execute-principal proposalId) (err ERR_CANT_EXECUTE))
    ;; start of real logic
    (var-set cityWallet newCityWallet)
    ;; end of real logic
    (try! (contract-call? .citycoin-auth mark-as-executed ))
    (ok true)
  )
)
```

**Comment by whoabuddy** [comment]
Hey @LNow thanks for these questions! 

1. I think it's cleaner to keep the list in `citycoin-auth` as that's where the checks will be performed, versus having to look up the map from `citycoin-core`.
2. The latter sounds like the best approach, since we will have the city wallet defined in `citycoin-core` which is technically the main way changes should be introduced. Then we can do a check for who is submitting it (or maybe create a separate function for each) and verify the auth passes in either case.

**Comment by whoabuddy** [comment]
This also made me think that we could create a generalized utility function like the ones we have now, e.g.

```lisp
(define-private (is-authorized-multisig)
  ;; verification code that interacts with citycoin-auth
  ;; returns true or false
)
```
