### ISSUE TITLE
Define intrinsic value of citycoin

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#18]
What is the incentive of miners to send STX around and received citycoins?

**Comment by cryptopanter** [comment]
Why taking the hassle of creating a token that is supposed to only inherit its intrinsic value from Stx?!... Why not just buying and storing Stx instead?

**Comment by 314159265359879** [comment]
I think people will use this because they love the city they are investing in. And they get credit for doing so in the form of the citycoin. 

I see citycoin as a charity.

**Comment by 314159265359879** [comment]
Perhaps you want people to have an ability to prove and show they have/had a certain amount of citycoins at a certain time. 

Allow people to mint an NFT that will include amount and the bitcoin block it is mined in. A proof of hodl if once has many of such NFT's or when the amount of citycoins in an account are shown to increase over time. 

Citycoin NFT - Owned 10,000 citycoins at the time of BTC block 700,000
Citycoin NFT - Owned 10,100 citycoins at the time of BTC block 701,000
etc.

**Comment by whoabuddy** [comment]
In the simplest sense, it comes down to a few things, @314159265359879 outlined some of this:

- anyone can mine citycoins for any reason they chose, it will be open to a global market and fairly launched, which opens up a new way to fund a city but also allows people to mine, purchase, speculate, or do whatever they see fit
- 30% of STX paid through mining would go to the city funds, so part of the incentive is directly tied to supporting the city in return for mining citycoins, and grows incentive for the city to pick up the bag
- the remaining 70% of STX are distributed to stackers, who can earn STX for their citycoins (not just a dead investment), and use that STX to earn BTC
- after picking up the bag, the city can choose what to do with it, we wanted to leave this open-ended on purpose in the beginning

This can expand to so much more in the future, but the key now is to keep it simple and see what happens 🙂

**Comment by friedger** [comment]
> I see citycoin as a charity.

That is a good reason. However, it is not very transparent how the 70% of my donation are used. Probably this will go to either earlier miners/donors or to those who paid most for the city coins on the secondary market. Do I want that as a donor?

**Comment by pstan26** [comment]
The 70% of STX being transferred go to the CityCoin Stackers, just like how BTC goes to STX Stackers in PoX. The 30% going to the City's wallet is what there should be the most transparency around imo -- and I believe we will see that be demanded from the markets naturally.

Re: the 70% transfer to CityCoins holders, the folks are mining and buying a lot early on are taking a big risk for their beliefs and could sell at any time.

**Comment by friedger** [comment]
@pstan26 I still don't get it. What is the value that the miners are hoping to get? Is it worth it that 70% of the minted value goes to CityCoin holders? CityCoin holder are happy for sure as long as there are miners to pay them. The 70% is not creating value for the network, isn't it?

**Comment by whoabuddy** [comment]
> What is the value that the miners are hoping to get?

The act of mining is the act of supporting the city. Flipping that question around, if you were a strong believer / supporter in a city, how could you actually contribute to it? This creates a mechanism where miners know that 30% of their spend is going to what they believe in, and 70% goes back to others who believe in the same. I think this concept is powerful and can be abstracted to other things as well. I anticipate there will be supporters, there will be speculators, and everything between.

> Is it worth it that 70% of the minted value goes to CityCoin holders?

Is it worth it that 100% of the minted value of STX goes to STX holders? We've seen that since miners receive a yield generating token versus "just another coin" is very successful, and this abstracts that idea to split part of those returns to a beneficial 3rd party.

> The 70% is not creating value for the network, isn't it?

This is starting simply but could quickly expand. One suggestion was to include a memo field for CityCoin miners, which would leave room to expand to app chains in the future. The first step is creating a positive feedback loop, and the easiest way to do that is by keeping things simple.

Plus, CityCoin holders would receive STX, which brings new holders into the ecosystem that would hopefully continue Stacking for BTC, which does create value for the network.

**Comment by whoabuddy** [comment]
Closing this one out as I think it's been thoroughly discussed, however if someone wants to restart the convo feel free.
