### ISSUE TITLE
Allow mining across multiple blocks

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin#4]
- the current configuration would require submitting a Stacks transaction in every block
- miners should be able to select an amount of STX and number of blocks to mine for
- miners should be registered in the mining map based on the rate and duration chosen

**Comment by whoabuddy** [comment]
Further clarifying with an example:

I want to mine for 144 blocks (~1 day / 24 hours) at 100 STX per block, the flow should be:

- I select 144 blocks and 100 STX per block
- the total transaction cost is 14,400 STX + transaction fee
- I mine the next 144 blocks at 100 STX per block

Thinking this through - it's going to require a check if the address is currently mining, and in the first version, this will likely be a one way transaction (set and forget).

If they are already mining, they'd get an error with the block height they'll finish mining at.

I'd like to approach this in a way that's **very simple** now, but leaves room for expansion of the logic later.

Open question: should this be a separate contract or rolled into the main citycoin one?

**Comment by pxydn** [comment]
Every citycoin will be its own contract. We don't need more than one contract per coin. This is definitely possible though

**Comment by LNow** [comment]
This one is quite tricky as it requires you to perform certain actions N times. Where N is number of blocks you want to mine.

Clarity does not support standard loops. The only loops which are supported are the one performed over lists, where separate function is executed on each element of that list (see [map](https://docs.stacks.co/references/language-functions#map), [fold](https://docs.stacks.co/references/language-functions#fold), [filter](https://docs.stacks.co/references/language-functions#filter))

Lists must be declared with size known upfront and because of that we have 2 options here:
1) Allow users to mine only for predefined number of blocks (ie. 1, 10, 144 (1 day), 432 (3 days). 1008 (7 days).
5 different functions (`mine-1`, `mine-10`, `mine-144`, `mine-432`, `mine-1008`) in which we iterate over lists of different lengths. It forces us to use hard limitation for how long user can mine. But no iteration is wasted.

2) Allow users to mine for no more than X blocks.
We iterate over big list (ie. with 1000 elements) and waste some of those iteration. For example if user choose to mine for 144 blocks we will waste 856 iterations.
Number of wasted iteration can be minimized by introducing some tiers ie. 144, 432, 1008, 2016 etc. but still some of them will be wasted.

I hope that Stacks 2.1 will bring lists slicing feature, as this would help us eliminate problem of wasted iterations described above.

**Comment by whoabuddy** [comment]
Interesting, this may be a V1 versus V2 type thought, where V1 is ideal for the MVP then after Stacks 2.1 we can revisit with new features to see if a different way is possible in V2.

If I had to chose today, I'd chose option 1 because it lines up well with the UI for sending a transaction, and seems cleaner (although more limited) on the back-end.

**Comment by pxydn** [comment]
agreed. we should go for #1 for now
