### ISSUE TITLE
Coinbase rewards should follow a token emission schedule

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin#6]
Similar to Bitcoin and Stacks (TBD)

- e.g. 1000 STX/block for first 4 yrs; 500 STX/block for following 4 yrs; 250 for the 4 yrs after that; and then 125 STX/block in perpetuity after that

**Comment by whoabuddy** [comment]
This will have the same properties as Stacks and suggest that others do the same, however it should be abstracted to Clarity constants so that future implementations have a choice.

The "halvings" will be synchronized with Bitcoin and Stacks, such that:

| Time Period | Reward | Notes |
| --- | --- | --- |
| First 10,000 BTC Blocks | 2,466 city coins | est. 3 months |
| until BTC Block 840,000 | 1,000 city coins | current height 5/3/2021 681,726 |
| after BTC Block 840,000 | 500 city coins | estimated 3/16/2024 | 
| after BTC Block 950,000 | 250 city coins | estimated 2028 | 
| after BTC Block 1,160,000 | 125 city coins | estaimted 2032, continues forever |

One challenge I see here - the current contract references the Stacks blockchain but does not use the Bitcoin block height, so that will need to be added unless there's a way to use a similar issuance schedule with Stacks block height?

**Comment by pxydn** [comment]
there should also be a supply cap, otherwise the coins will inflate over time.

**Comment by LNow** [comment]
> One challenge I see here - the current contract references the Stacks blockchain but does not use the Bitcoin block height, so that will need to be added unless there's a way to use a similar issuance schedule with Stacks block height?

This should not be a problem. Clarity have a dedicated keyword `burn-block-height` for that ([docs](https://docs.stacks.co/references/language-keywords#burn-block-height)).
If we build token emission logic based on BTC blocks, then we have to remember about BTC flash blocks.

**Comment by 314159265359879** [comment]
> 
> 
> This will have the same properties as Stacks and suggest that others do the same, however it should be abstracted to Clarity constants so that future implementations have a choice.
> 
> The "halvings" will be synchronized with Bitcoin and Stacks, such that:
> Time Period 	Reward 	Notes
> First 10,000 BTC Blocks 	2,466 city coins 	est. 3 months
> until BTC Block 840,000 	1,000 city coins 	current height 5/3/2021 681,726
> after BTC Block 840,000 	500 city coins 	estimated 3/16/2024
> after BTC Block 950,000 	250 city coins 	estimated 2028
> after BTC Block 1,160,000 	125 city coins 	estaimted 2032, continues forever
> 
> One challenge I see here - the current contract references the Stacks blockchain but does not use the Bitcoin block height, so that will need to be added unless there's a way to use a similar issuance schedule with Stacks block height?

The first 10000 BTC blocks there were 2000 stx awarded per bitcoin block. That calculated to 2466 stx per stacks block. I think the rest of the awards are based on award per BTC block.

Does the POXL contract have the same advantage if in a BTC block no citycoins are mined, the award from unmined blocks is added to the next block until it is mined?

> 
> 
> there should also be a supply cap, otherwise the coins will inflate over time.

A small inflation rate isn't necessarily a problem. Will there also be purposeful burning of citycoins (such as for BNS on stacks)? Or could we imagine such a purpose?


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Werner\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Werner\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Start block | end block | BTC blocks | reward per BTC block | Total rewards | Cumulative |  
-- | -- | -- | -- | -- | -- | --
690000 | 700000 | 10000 | 2000 | 20000000 | 20000000 |  
690000 | 840000 | 150000 | 1000 | 150000000 | 170000000 |  
840000 | 950000 | 110000 | 500 | 55000000 | 225000000 |  
950000 | 1160000 | 210000 | 250 | 52500000 | 277500000 |  
1160000 |   |   | 125 |   |   |  
1 year |   | 52560 | 125 | 6570000 | 2,37% | inflation rate in 2032



</body>

</html>

**Comment by whoabuddy** [comment]
> If we build token emission logic based on BTC blocks, then we have to remember about BTC flash blocks problem.

@LNow I still think this is the preferable way to go by using BTC blocks, since BTC is the measuring stick for all other crypto anyway 🙃📏 Wouldn't the flash blocks problem be a problem either way, just manifested differently?

> The first 10000 BTC blocks there were 2000 stx awarded per bitcoin block. That calculated to 2466 stx per stacks block. I think the rest of the awards are based on award per BTC block.

@314159265359879 I was wondering where the extra 466 came from, I didn't see a variance in what was being reported but also haven't dug that deep into the data. The bigger point here is that we want to run a bonus round for the beginning.

> Does the POXL contract have the same advantage if in a BTC block no citycoins are mined, the award from unmined blocks is added to the next block until it is mined?

No, I believe in the current state if no city coins are mined then it'd be a "missed" reward for Stackers and that's all. I do like this idea as an incentive for miners.

> A small inflation rate isn't necessarily a problem. Will there also be purposeful burning of citycoins (such as for BNS on stacks)? Or could we imagine such a purpose?

Ideally, things like this will happen organically. If we can mine the city coin into existence and get the city to take the funds, the natural next question is - what can we do with these? (and there's been some great ideas already)

**Comment by whoabuddy** [comment]
Linking discussion about the supply cap here: #17

**Comment by whoabuddy** [comment]
After reviewing how this would function as part of #35, I'm not confident that BTC blocks are the best measuring stick, given everything else in the contract operates off of Stacks blocks.

While for this project, the next halving at BTC Block 840,000 is still a good target (~3 years out), future coins would suffer from less time before their first halving, and the values would need to be updated once we pass that block.

A more sustainable solution is to use the same 210,000 block periods for halvings, but to start the process based on when the coin launches as part of the mining activation, then calculate the 10,000 block bonus period and 210,000 block halvings based on that starting stacks block height.

The issuance schedule in the PRD needs to be updated as well as the `get-coinbase-amount` function, related tests, etc.
